version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smartloan-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - smartloan_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  smartloan_pgdata:
